check new approach to work with directory

diff --git a/.github/shared-steps/action.yml b/.github/shared-steps/action.yml
--- a/.github/shared-steps/action.yml
+++ b/.github/shared-steps/action.yml
@@ -1,6 +1,9 @@
 name: Shared Steps
 description: run ui tests
 inputs:
+  working_directory:
+    description: 'The working directory for the shared steps'
+    required: true
   project:
     description: 'Playwright project to run tests for'
     required: true
@@ -40,6 +43,7 @@ runs:
         shell: bash
         id: ticket-statuses
         run: |
+          cd ${{ inputs.working_directory }}
           npx ts-node automation/scripts/GetListOfJirasToSkip.ts
           ticketStatusesFile="ticketStatuses.json"
           if [[ -f "$ticketStatusesFile" ]]; then
@@ -142,32 +146,32 @@ runs:
           if_true: test_slack_notifications
           if_false: ts_website_automation
 
-      - name: Slack Notification for UI tests production
-        id: slack-notification
-        if: ${{ (!github.event.pull_request.draft && ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && failure()))) }}
-        uses: rtCamp/action-slack-notify@v2.2.0
-        env:
-          SLACK_USERNAME: Tests execution report
-          SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
-          SLACK_CHANNEL: ${{ steps.slack_channel_production.outputs.value }}
-          SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
-          SLACK_COLOR: ${{ job.status }}
-          SLACK_MESSAGE: "Total: ${{ env.TOTAL }} | ✅Passed: ${{ env.PASSED }} | ❌Failed: ${{ env.FAILED }} | ⏭️Skipped: ${{ env.SKIPPED }} | 🔁Flaky: ${{ env.FLAKY }} \n:eyes: link for report: https://tech-stack-dev.github.io/ts-website-automation/ui_tests_playwright/automation/reports/regression/${{ env.CURRENT_DAY }}/${{ env.CURRENT_TIME }}/index.html"
-          SLACK_TITLE: ${{ inputs.slack_title }}
-          MSG_MINIMAL: true
-          SLACK_FOOTER: TS website
+      # - name: Slack Notification for UI tests production
+      #   id: slack-notification
+      #   if: ${{ (!github.event.pull_request.draft && ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && failure()))) }}
+      #   uses: rtCamp/action-slack-notify@v2.2.0
+      #   env:
+      #     SLACK_USERNAME: Tests execution report
+      #     SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
+      #     SLACK_CHANNEL: ${{ steps.slack_channel_production.outputs.value }}
+      #     SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
+      #     SLACK_COLOR: ${{ job.status }}
+      #     SLACK_MESSAGE: "Total: ${{ env.TOTAL }} | ✅Passed: ${{ env.PASSED }} | ❌Failed: ${{ env.FAILED }} | ⏭️Skipped: ${{ env.SKIPPED }} | 🔁Flaky: ${{ env.FLAKY }} \n:eyes: link for report: https://tech-stack-dev.github.io/ts-website-automation/ui_tests_playwright/automation/reports/regression/${{ env.CURRENT_DAY }}/${{ env.CURRENT_TIME }}/index.html"
+      #     SLACK_TITLE: ${{ inputs.slack_title }}
+      #     MSG_MINIMAL: true
+      #     SLACK_FOOTER: TS website
 
-      - name: Slack Notification for UI tests automation
-        if: ${{ (!github.event.pull_request.draft && ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && failure()))) }}
-        uses: rtCamp/action-slack-notify@v2.2.0
-        env:
-          SLACK_USERNAME: Tests execution report
-          SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
-          SLACK_CHANNEL: ${{ steps.slack_channel_automation.outputs.value }}
-          SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
-          SLACK_COLOR: ${{ job.status }}
-          SLACK_MESSAGE: "Total: ${{ env.TOTAL }} | ✅Passed: ${{ env.PASSED }} | ❌Failed: ${{ env.FAILED }} | ⏭️Skipped: ${{ env.SKIPPED }} | 🔁Flaky: ${{ env.FLAKY }} \n:eyes: link for report: https://tech-stack-dev.github.io/ts-website-automation/ui_tests_playwright/automation/reports/regression/${{ env.CURRENT_DAY }}/${{ env.CURRENT_TIME }}/index.html"
-          SLACK_TITLE: ${{ inputs.slack_title }}
-          MSG_MINIMAL: true
-          SLACK_FOOTER: TS website
+      # - name: Slack Notification for UI tests automation
+      #   if: ${{ (!github.event.pull_request.draft && ((github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') || (github.event_name == 'pull_request' && failure()))) }}
+      #   uses: rtCamp/action-slack-notify@v2.2.0
+      #   env:
+      #     SLACK_USERNAME: Tests execution report
+      #     SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
+      #     SLACK_CHANNEL: ${{ steps.slack_channel_automation.outputs.value }}
+      #     SLACK_ICON_EMOJI: ${{ steps.slack_icon_emoji.outputs.value }}
+      #     SLACK_COLOR: ${{ job.status }}
+      #     SLACK_MESSAGE: "Total: ${{ env.TOTAL }} | ✅Passed: ${{ env.PASSED }} | ❌Failed: ${{ env.FAILED }} | ⏭️Skipped: ${{ env.SKIPPED }} | 🔁Flaky: ${{ env.FLAKY }} \n:eyes: link for report: https://tech-stack-dev.github.io/ts-website-automation/ui_tests_playwright/automation/reports/regression/${{ env.CURRENT_DAY }}/${{ env.CURRENT_TIME }}/index.html"
+      #     SLACK_TITLE: ${{ inputs.slack_title }}
+      #     MSG_MINIMAL: true
+      #     SLACK_FOOTER: TS website
   
